--------------------------------------------------------------------
-- |----------------------------------------------------------------
-- | Product ID: GSDM
-- | Project: CBA FRTB EDM 
-- | Date: 10-May-2018
-- | Requested By: 
-- | Approved By: 
-- | Prepared By: GoldenSource
-- |----------------------------------------------------------------
-- | Tables Affected: 
-- |----------------------------------------------------------------
-- History     :
---------------------------------------------------------------------
-- S.No.  DefectID             Date       By              Description
-- --------------------------------------------------------------------
-- 1.     

SET SCAN OFF;
SET ECHO ON;
SET DEFINE OFF;

--------------------------------------------------------------------

Insert into FT_T_ISGR (ISS_GRP_OID, ISS_GRP_ID, LAST_CHG_TMS, LAST_CHG_USR_ID, GRP_PURP_TYP, START_TMS, GRP_NME, GRP_DESC, DATA_STAT_TYP, DATA_SRC_ID, DWDF_OID) Values ('WSS=ISGR01', 'CBATST02', sysdate, 'CBA', 'REQUEST', sysdate, 'WSS_SYD_FX', 'Wallstreet Publishing Sydney FX', 'ACTIVE', 'CBA', 'CBA====WSS');
Insert into FT_T_ISGR (ISS_GRP_OID, ISS_GRP_ID, LAST_CHG_TMS, LAST_CHG_USR_ID, GRP_PURP_TYP, START_TMS, GRP_NME, GRP_DESC, DATA_STAT_TYP, DATA_SRC_ID, DWDF_OID) Values ('WSS=ISGR02', 'CBATST03', sysdate, 'CBA', 'REQUEST', sysdate, 'WSS_SYD_MM', 'Wallstreet Publishing Sydney MM', 'ACTIVE', 'CBA', 'CBA====WSS');
Insert into FT_T_ISGR (ISS_GRP_OID, ISS_GRP_ID, LAST_CHG_TMS, LAST_CHG_USR_ID, GRP_PURP_TYP, START_TMS, GRP_NME, GRP_DESC, DATA_STAT_TYP, DATA_SRC_ID, DWDF_OID) Values ('WSS=ISGR03', 'CBATST04', sysdate, 'CBA', 'REQUEST', sysdate, 'WSS_NY_FX', 'Wallstreet Publishing New York FX', 'ACTIVE', 'CBA', 'CBA====WSS');
Insert into FT_T_ISGR (ISS_GRP_OID, ISS_GRP_ID, LAST_CHG_TMS, LAST_CHG_USR_ID, GRP_PURP_TYP, START_TMS, GRP_NME, GRP_DESC, DATA_STAT_TYP, DATA_SRC_ID, DWDF_OID) Values ('WSS=ISGR04', 'CBATST05', sysdate, 'CBA', 'REQUEST', sysdate, 'WSS_NY_MM', 'Wallstreet Publishing New York MM', 'ACTIVE', 'CBA', 'CBA====WSS');
Insert into FT_T_ISGR (ISS_GRP_OID, ISS_GRP_ID, LAST_CHG_TMS, LAST_CHG_USR_ID, GRP_PURP_TYP, START_TMS, GRP_NME, GRP_DESC, DATA_STAT_TYP, DATA_SRC_ID, DWDF_OID) Values ('WSS=ISGR05', 'CBATST06', sysdate, 'CBA', 'REQUEST', sysdate, 'WSS_LDN_FX', 'Wallstreet Publishing London FX', 'ACTIVE', 'CBA', 'CBA====WSS');
Insert into FT_T_ISGR (ISS_GRP_OID, ISS_GRP_ID, LAST_CHG_TMS, LAST_CHG_USR_ID, GRP_PURP_TYP, START_TMS, GRP_NME, GRP_DESC, DATA_STAT_TYP, DATA_SRC_ID, DWDF_OID) Values ('WSS=ISGR06', 'CBATST07', sysdate, 'CBA', 'REQUEST', sysdate, 'WSS_LDN_MM', 'Wallstreet Publishing London MM', 'ACTIVE', 'CBA', 'CBA====WSS');
Insert into FT_T_ISGR (ISS_GRP_OID, ISS_GRP_ID, LAST_CHG_TMS, LAST_CHG_USR_ID, GRP_PURP_TYP, START_TMS, GRP_NME, GRP_DESC, DATA_STAT_TYP, DATA_SRC_ID, DWDF_OID) Values ('WSS=ISGR07', 'CBATST08', sysdate, 'CBA', 'REQUEST', sysdate, 'WSS_SAL_MM', 'Wallstreet Publishing SAL MM', 'ACTIVE', 'CBA', 'CBA====WSS');
Insert into FT_T_ISGR (ISS_GRP_OID, ISS_GRP_ID, LAST_CHG_TMS, LAST_CHG_USR_ID, GRP_PURP_TYP, START_TMS, GRP_NME, GRP_DESC, DATA_STAT_TYP, DATA_SRC_ID, DWDF_OID) Values ('WSS=ISGR08', 'CBATST09', sysdate, 'CBA', 'REQUEST', sysdate, 'WSS_LVR_MM', 'Wallstreet Publishing LVR MM', 'ACTIVE', 'CBA', 'CBA====WSS');
