--select * from fT_T_srpp where srle_oid in (select srle_oid from fT_T_srle where sec_role_nme in ('CBA_OD_Role','CBA_MRU_Role','CBA_FO_Role'));
Insert into FT_T_SRPP (SRLE_OID,SPRF_OID,START_TMS,END_TMS,LAST_CHG_TMS,LAST_CHG_USR_ID,SEC_ROLE_PROF_DESC,SEC_PROF_VAL_TXT,ENTITY_TYP,ENABLE_AUDIT_IND,SRPP_OID) values ((select srle_oid from fT_T_srle where sec_role_nme = 'CBA_MRU_Role'),(select sprf_oid from fT_T_sprf where sec_prof_nme ='InstrumentGroup'),to_date('01/JAN/17','DD/MON/RR'),null,to_date('12/APR/18','DD/MON/RR'),'user1','SimpleMakerChecker','be',null,null,new_oid);

Insert into FT_T_SRPP (SRLE_OID,SPRF_OID,START_TMS,END_TMS,LAST_CHG_TMS,LAST_CHG_USR_ID,SEC_ROLE_PROF_DESC,SEC_PROF_VAL_TXT,ENTITY_TYP,ENABLE_AUDIT_IND,SRPP_OID) values ((select srle_oid from fT_T_srle where sec_role_nme = 'CBA_OD_Role'),(select sprf_oid from fT_T_sprf where sec_prof_nme ='InstrumentGroup'),to_date('01/JAN/17','DD/MON/RR'),null,to_date('10/APR/18','DD/MON/RR'),'user1','SimpleMakerChecker','be',null,null,new_oid);
Insert into FT_T_SRPP (SRLE_OID,SPRF_OID,START_TMS,END_TMS,LAST_CHG_TMS,LAST_CHG_USR_ID,SEC_ROLE_PROF_DESC,SEC_PROF_VAL_TXT,ENTITY_TYP,ENABLE_AUDIT_IND,SRPP_OID) values ((select srle_oid from fT_T_srle where sec_role_nme = 'CBA_MRU_Role'),(select sprf_oid from fT_T_sprf where sec_prof_nme ='ApplicationLibrary'),to_date('01/JAN/17','DD/MON/RR'),null,to_date('12/APR/18','DD/MON/RR'),'user1','SimpleMakerChecker','be',null,null,new_oid);
Insert into FT_T_SRPP (SRLE_OID,SPRF_OID,START_TMS,END_TMS,LAST_CHG_TMS,LAST_CHG_USR_ID,SEC_ROLE_PROF_DESC,SEC_PROF_VAL_TXT,ENTITY_TYP,ENABLE_AUDIT_IND,SRPP_OID) values ((select srle_oid from fT_T_srle where sec_role_nme = 'CBA_MRU_Role'),(select sprf_oid from fT_T_sprf where sec_prof_nme ='CalendarDefinition'),to_date('01/JAN/17','DD/MON/RR'),null,to_date('12/APR/18','DD/MON/RR'),'user1','SimpleMakerChecker','be',null,null,new_oid);
Insert into FT_T_SRPP (SRLE_OID,SPRF_OID,START_TMS,END_TMS,LAST_CHG_TMS,LAST_CHG_USR_ID,SEC_ROLE_PROF_DESC,SEC_PROF_VAL_TXT,ENTITY_TYP,ENABLE_AUDIT_IND,SRPP_OID) values ((select srle_oid from fT_T_srle where sec_role_nme = 'CBA_MRU_Role'),(select sprf_oid from fT_T_sprf where sec_prof_nme ='ConfigureRules'),to_date('01/JAN/17','DD/MON/RR'),null,to_date('12/APR/18','DD/MON/RR'),'user1','SimpleMakerChecker','be',null,null,new_oid);
Insert into FT_T_SRPP (SRLE_OID,SPRF_OID,START_TMS,END_TMS,LAST_CHG_TMS,LAST_CHG_USR_ID,SEC_ROLE_PROF_DESC,SEC_PROF_VAL_TXT,ENTITY_TYP,ENABLE_AUDIT_IND,SRPP_OID) values ((select srle_oid from fT_T_srle where sec_role_nme = 'CBA_MRU_Role'),(select sprf_oid from fT_T_sprf where sec_prof_nme ='CurveSurface'),to_date('01/JAN/17','DD/MON/RR'),null,to_date('12/APR/18','DD/MON/RR'),'user1','SimpleMakerChecker','be',null,null,new_oid);
Insert into FT_T_SRPP (SRLE_OID,SPRF_OID,START_TMS,END_TMS,LAST_CHG_TMS,LAST_CHG_USR_ID,SEC_ROLE_PROF_DESC,SEC_PROF_VAL_TXT,ENTITY_TYP,ENABLE_AUDIT_IND,SRPP_OID) values ((select srle_oid from fT_T_srle where sec_role_nme = 'CBA_MRU_Role'),(select sprf_oid from fT_T_sprf where sec_prof_nme ='FullInstrument'),to_date('01/JAN/17','DD/MON/RR'),null,to_date('12/APR/18','DD/MON/RR'),'user1','SimpleMakerChecker','be',null,null,new_oid);
Insert into FT_T_SRPP (SRLE_OID,SPRF_OID,START_TMS,END_TMS,LAST_CHG_TMS,LAST_CHG_USR_ID,SEC_ROLE_PROF_DESC,SEC_PROF_VAL_TXT,ENTITY_TYP,ENABLE_AUDIT_IND,SRPP_OID) values ((select srle_oid from fT_T_srle where sec_role_nme = 'CBA_MRU_Role'),(select sprf_oid from fT_T_sprf where sec_prof_nme ='Matrix'),to_date('01/JAN/17','DD/MON/RR'),null,to_date('12/APR/18','DD/MON/RR'),'user1','SimpleMakerChecker','be',null,null,new_oid);
Insert into FT_T_SRPP (SRLE_OID,SPRF_OID,START_TMS,END_TMS,LAST_CHG_TMS,LAST_CHG_USR_ID,SEC_ROLE_PROF_DESC,SEC_PROF_VAL_TXT,ENTITY_TYP,ENABLE_AUDIT_IND,SRPP_OID) values ((select srle_oid from fT_T_srle where sec_role_nme = 'CBA_MRU_Role'),(select sprf_oid from fT_T_sprf where sec_prof_nme ='PriceValidationRules'),to_date('01/JAN/17','DD/MON/RR'),null,to_date('12/APR/18','DD/MON/RR'),'user1','SimpleMakerChecker','be',null,null,new_oid);
Insert into FT_T_SRPP (SRLE_OID,SPRF_OID,START_TMS,END_TMS,LAST_CHG_TMS,LAST_CHG_USR_ID,SEC_ROLE_PROF_DESC,SEC_PROF_VAL_TXT,ENTITY_TYP,ENABLE_AUDIT_IND,SRPP_OID) values ((select srle_oid from fT_T_srle where sec_role_nme = 'CBA_MRU_Role'),(select sprf_oid from fT_T_sprf where sec_prof_nme ='PricingModelUsage'),to_date('01/JAN/17','DD/MON/RR'),null,to_date('12/APR/18','DD/MON/RR'),'user1','SimpleMakerChecker','be',null,null,new_oid);
Insert into FT_T_SRPP (SRLE_OID,SPRF_OID,START_TMS,END_TMS,LAST_CHG_TMS,LAST_CHG_USR_ID,SEC_ROLE_PROF_DESC,SEC_PROF_VAL_TXT,ENTITY_TYP,ENABLE_AUDIT_IND,SRPP_OID) values ((select srle_oid from fT_T_srle where sec_role_nme = 'CBA_MRU_Role'),(select sprf_oid from fT_T_sprf where sec_prof_nme ='SnapTime'),to_date('01/JAN/17','DD/MON/RR'),null,to_date('12/APR/18','DD/MON/RR'),'user1','SimpleMakerChecker','be',null,null,new_oid);
Insert into FT_T_SRPP (SRLE_OID,SPRF_OID,START_TMS,END_TMS,LAST_CHG_TMS,LAST_CHG_USR_ID,SEC_ROLE_PROF_DESC,SEC_PROF_VAL_TXT,ENTITY_TYP,ENABLE_AUDIT_IND,SRPP_OID) values ((select srle_oid from fT_T_srle where sec_role_nme = 'CBA_MRU_Role'),(select sprf_oid from fT_T_sprf where sec_prof_nme ='ApplicationDefinition'),to_date('01/JAN/17','DD/MON/RR'),null,to_date('12/APR/18','DD/MON/RR'),'user1','SimpleMakerChecker','be',null,null,new_oid);
Insert into FT_T_SRPP (SRLE_OID,SPRF_OID,START_TMS,END_TMS,LAST_CHG_TMS,LAST_CHG_USR_ID,SEC_ROLE_PROF_DESC,SEC_PROF_VAL_TXT,ENTITY_TYP,ENABLE_AUDIT_IND,SRPP_OID) values ((select srle_oid from fT_T_srle where sec_role_nme = 'CBA_OD_Role'),(select sprf_oid from fT_T_sprf where sec_prof_nme ='all'),to_date('01/JAN/17','DD/MON/RR'),null,to_date('29/MAR/18','DD/MON/RR'),'user1',null,'editable',null,null,new_oid);
Insert into FT_T_SRPP (SRLE_OID,SPRF_OID,START_TMS,END_TMS,LAST_CHG_TMS,LAST_CHG_USR_ID,SEC_ROLE_PROF_DESC,SEC_PROF_VAL_TXT,ENTITY_TYP,ENABLE_AUDIT_IND,SRPP_OID) values ((select srle_oid from fT_T_srle where sec_role_nme = 'CBA_OD_Role'),(select sprf_oid from fT_T_sprf where sec_prof_nme ='admin'),to_date('01/JAN/17','DD/MON/RR'),null,to_date('29/MAR/18','DD/MON/RR'),'user1',null,'editable',null,null,new_oid);
Insert into FT_T_SRPP (SRLE_OID,SPRF_OID,START_TMS,END_TMS,LAST_CHG_TMS,LAST_CHG_USR_ID,SEC_ROLE_PROF_DESC,SEC_PROF_VAL_TXT,ENTITY_TYP,ENABLE_AUDIT_IND,SRPP_OID) values ((select srle_oid from fT_T_srle where sec_role_nme = 'CBA_MRU_Role'),(select sprf_oid from fT_T_sprf where sec_prof_nme ='all'),to_date('01/JAN/17','DD/MON/RR'),null,to_date('29/MAR/18','DD/MON/RR'),'user1',null,'editable',null,null,new_oid);
Insert into FT_T_SRPP (SRLE_OID,SPRF_OID,START_TMS,END_TMS,LAST_CHG_TMS,LAST_CHG_USR_ID,SEC_ROLE_PROF_DESC,SEC_PROF_VAL_TXT,ENTITY_TYP,ENABLE_AUDIT_IND,SRPP_OID) values ((select srle_oid from fT_T_srle where sec_role_nme = 'CBA_MRU_Role'),(select sprf_oid from fT_T_sprf where sec_prof_nme ='mds'),to_date('01/JAN/17','DD/MON/RR'),null,to_date('29/MAR/18','DD/MON/RR'),'user1',null,'editable',null,null,new_oid);
Insert into FT_T_SRPP (SRLE_OID,SPRF_OID,START_TMS,END_TMS,LAST_CHG_TMS,LAST_CHG_USR_ID,SEC_ROLE_PROF_DESC,SEC_PROF_VAL_TXT,ENTITY_TYP,ENABLE_AUDIT_IND,SRPP_OID) values ((select srle_oid from fT_T_srle where sec_role_nme = 'CBA_FO_Role'),(select sprf_oid from fT_T_sprf where sec_prof_nme ='all'),to_date('01/JAN/17','DD/MON/RR'),null,to_date('29/MAR/18','DD/MON/RR'),'user1',null,'read-only',null,null,new_oid);
Insert into FT_T_SRPP (SRLE_OID,SPRF_OID,START_TMS,END_TMS,LAST_CHG_TMS,LAST_CHG_USR_ID,SEC_ROLE_PROF_DESC,SEC_PROF_VAL_TXT,ENTITY_TYP,ENABLE_AUDIT_IND,SRPP_OID) values ((select srle_oid from fT_T_srle where sec_role_nme = 'CBA_OD_Role'),(select sprf_oid from fT_T_sprf where sec_prof_nme ='ApplicationDefinition'),to_date('01/JAN/17','DD/MON/RR'),null,to_date('12/APR/18','DD/MON/RR'),'user1','SimpleMakerChecker','be',null,null,new_oid);
Insert into FT_T_SRPP (SRLE_OID,SPRF_OID,START_TMS,END_TMS,LAST_CHG_TMS,LAST_CHG_USR_ID,SEC_ROLE_PROF_DESC,SEC_PROF_VAL_TXT,ENTITY_TYP,ENABLE_AUDIT_IND,SRPP_OID) values ((select srle_oid from fT_T_srle where sec_role_nme = 'CBA_OD_Role'),(select sprf_oid from fT_T_sprf where sec_prof_nme ='ApplicationLibrary'),to_date('01/JAN/17','DD/MON/RR'),null,to_date('12/APR/18','DD/MON/RR'),'user1','SimpleMakerChecker','be',null,null,new_oid);
Insert into FT_T_SRPP (SRLE_OID,SPRF_OID,START_TMS,END_TMS,LAST_CHG_TMS,LAST_CHG_USR_ID,SEC_ROLE_PROF_DESC,SEC_PROF_VAL_TXT,ENTITY_TYP,ENABLE_AUDIT_IND,SRPP_OID) values ((select srle_oid from fT_T_srle where sec_role_nme = 'CBA_OD_Role'),(select sprf_oid from fT_T_sprf where sec_prof_nme ='CalendarDefinition'),to_date('01/JAN/17','DD/MON/RR'),null,to_date('12/APR/18','DD/MON/RR'),'user1','SimpleMakerChecker','be',null,null,new_oid);
Insert into FT_T_SRPP (SRLE_OID,SPRF_OID,START_TMS,END_TMS,LAST_CHG_TMS,LAST_CHG_USR_ID,SEC_ROLE_PROF_DESC,SEC_PROF_VAL_TXT,ENTITY_TYP,ENABLE_AUDIT_IND,SRPP_OID) values ((select srle_oid from fT_T_srle where sec_role_nme = 'CBA_OD_Role'),(select sprf_oid from fT_T_sprf where sec_prof_nme ='ConfigureRules'),to_date('01/JAN/17','DD/MON/RR'),null,to_date('12/APR/18','DD/MON/RR'),'user1','SimpleMakerChecker','be',null,null,new_oid);
Insert into FT_T_SRPP (SRLE_OID,SPRF_OID,START_TMS,END_TMS,LAST_CHG_TMS,LAST_CHG_USR_ID,SEC_ROLE_PROF_DESC,SEC_PROF_VAL_TXT,ENTITY_TYP,ENABLE_AUDIT_IND,SRPP_OID) values ((select srle_oid from fT_T_srle where sec_role_nme = 'CBA_OD_Role'),(select sprf_oid from fT_T_sprf where sec_prof_nme ='CurveSurface'),to_date('01/JAN/17','DD/MON/RR'),null,to_date('12/APR/18','DD/MON/RR'),'user1','SimpleMakerChecker','be',null,null,new_oid);
Insert into FT_T_SRPP (SRLE_OID,SPRF_OID,START_TMS,END_TMS,LAST_CHG_TMS,LAST_CHG_USR_ID,SEC_ROLE_PROF_DESC,SEC_PROF_VAL_TXT,ENTITY_TYP,ENABLE_AUDIT_IND,SRPP_OID) values ((select srle_oid from fT_T_srle where sec_role_nme = 'CBA_OD_Role'),(select sprf_oid from fT_T_sprf where sec_prof_nme ='FullInstrument'),to_date('01/JAN/17','DD/MON/RR'),null,to_date('12/APR/18','DD/MON/RR'),'user1','SimpleMakerChecker','be',null,null,new_oid);
Insert into FT_T_SRPP (SRLE_OID,SPRF_OID,START_TMS,END_TMS,LAST_CHG_TMS,LAST_CHG_USR_ID,SEC_ROLE_PROF_DESC,SEC_PROF_VAL_TXT,ENTITY_TYP,ENABLE_AUDIT_IND,SRPP_OID) values ((select srle_oid from fT_T_srle where sec_role_nme = 'CBA_OD_Role'),(select sprf_oid from fT_T_sprf where sec_prof_nme ='Matrix'),to_date('01/JAN/17','DD/MON/RR'),null,to_date('12/APR/18','DD/MON/RR'),'user1','SimpleMakerChecker','be',null,null,new_oid);
Insert into FT_T_SRPP (SRLE_OID,SPRF_OID,START_TMS,END_TMS,LAST_CHG_TMS,LAST_CHG_USR_ID,SEC_ROLE_PROF_DESC,SEC_PROF_VAL_TXT,ENTITY_TYP,ENABLE_AUDIT_IND,SRPP_OID) values ((select srle_oid from fT_T_srle where sec_role_nme = 'CBA_OD_Role'),(select sprf_oid from fT_T_sprf where sec_prof_nme ='PriceValidationRules'),to_date('01/JAN/17','DD/MON/RR'),null,to_date('12/APR/18','DD/MON/RR'),'user1','SimpleMakerChecker','be',null,null,new_oid);
Insert into FT_T_SRPP (SRLE_OID,SPRF_OID,START_TMS,END_TMS,LAST_CHG_TMS,LAST_CHG_USR_ID,SEC_ROLE_PROF_DESC,SEC_PROF_VAL_TXT,ENTITY_TYP,ENABLE_AUDIT_IND,SRPP_OID) values ((select srle_oid from fT_T_srle where sec_role_nme = 'CBA_OD_Role'),(select sprf_oid from fT_T_sprf where sec_prof_nme ='PricingModelUsage'),to_date('01/JAN/17','DD/MON/RR'),null,to_date('12/APR/18','DD/MON/RR'),'user1','SimpleMakerChecker','be',null,null,new_oid);
Insert into FT_T_SRPP (SRLE_OID,SPRF_OID,START_TMS,END_TMS,LAST_CHG_TMS,LAST_CHG_USR_ID,SEC_ROLE_PROF_DESC,SEC_PROF_VAL_TXT,ENTITY_TYP,ENABLE_AUDIT_IND,SRPP_OID) values ((select srle_oid from fT_T_srle where sec_role_nme = 'CBA_OD_Role'),(select sprf_oid from fT_T_sprf where sec_prof_nme ='SnapTime'),to_date('01/JAN/17','DD/MON/RR'),null,to_date('12/APR/18','DD/MON/RR'),'user1','SimpleMakerChecker','be',null,null,new_oid);


select * from ft_t_sprf;