

SET SCAN OFF;
SET DEFINE OFF;



Insert into FT_T_ISGR (ISS_GRP_OID, ISS_GRP_ID, LAST_CHG_TMS, LAST_CHG_USR_ID, GRP_PURP_TYP, START_TMS, GRP_NME, GRP_DESC, DATA_STAT_TYP, DATA_SRC_ID, DWDF_OID) Values ('RCVA==1665', '1665', sysdate, 'CBA', 'REQUEST', sysdate, 'SYD_MAT_DSS_1215_INTRDAY', 'SYD_MAT_DSS_1215_INTRDAY', 'ACTIVE', 'CBA', 'Default');
